openapi: 3.0.3
info:
  title: API Specification for personal tracking
  version: 1.0-SNAPSHOT
servers:
  - url: https://localhost:3030/api/v1
  - url: https://produccion/api/v1
tags:
  - name: Gastos
    description: Agrupación de gastos
paths:
  /bills:
    get:
      tags:
        - bills
      summary: Get bill information information
      description: Get all bills available
      operationId: getBills
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bills'
    post:
      tags:
        - bills
      summary: Register new bill
      description: Registers a new bill with a type
      operationId: postBill
      requestBody:
        description: Amount and type of bill
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BillDto'
        required: true
      responses:
        200:
          description: Bill successfully registered
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountNotFoundError'

  /weights:
    get:
      tags:
        - weights
      summary: Get weight tracking information
      description: Get all weights available
      operationId: getWeights
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Weights'
    post:
      tags:
        - weights
      summary: Register new weight
      description: Registers a new weight
      operationId: postWeight
      requestBody:
        description: kilograms
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WeightDto'
        required: true
      responses:
        200:
          description: Weight successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeightResponse'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountNotFoundError'

  /billType:
    get:
      tags:
        - bill types
      summary: Get bill type information
      description: Get all bill types available
      operationId: getBillTypes
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillTypes'
    post:
      tags:
        - bill types
      summary: Get bill type information
      description: Get all bill types available
      operationId: postBillType
      requestBody:
        description: bill type info
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BillTypeDto'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillTypeDto'
components:
  schemas:
    Bills:
      type: array
      items:
        $ref: '#/components/schemas/BillDto'
    BillDto:
      type: object
      required:
        - billTypeDescription
        - depositAmount
        - date
      properties:
        billTypeDescription:
          type: string
        depositAmount:
          type: number
        date:
          type: string
          format: date-time
    Weights:
      type: array
      items:
        $ref: '#/components/schemas/WeightResponse'
    AccountNotFoundError:
      type: object
      properties:
        message:
          type: string
    BillTypeDto:
      type: object
      required:
        - billTypeDescription
        - billTypeCategory
      properties:
        billTypeDescription:
          type: string
        billTypeCategory:
          type: string
    BillTypes:
      type: array
      items:
        $ref: '#/components/schemas/BillTypeDto'
    WeightDto:
      type: object
      properties:
        weight:
          type: number
        date:
          type: string
          format: date
    WeightResponse:
      type: object
      properties:
        weight:
          type: number
        date:
          type: string
          format: date


